# Statistical Tests

## 1. Chi-squared Test

##### Purpose: To find is there any siginifant association/relationship between 2 qualitative variables.

In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import scipy.stats as stats

In [4]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [6]:
tips_data = sns.load_dataset('tips')
tips_data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 1. Perform Initial Analysis

In [27]:
sex_smoker_data = pd.crosstab(index = tips_data.sex, columns = tips_data.smoker)
sex_smoker_data

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [35]:
chi_square_tscore,pval,df,exp_table = stats.chi2_contingency(sex_smoker_data)
print('Chi-square score is {}.\np value is {}.\ndf is {}.\nExpected table is \n{}'.format(chi_square_tscore,pval,df,exp_table))

Chi-square score is 0.008763290531773594.
p value is 0.925417020494423.
df is 1.
Expected table is 
[[59.84016393 97.15983607]
 [33.15983607 53.84016393]]


In [36]:
if pval<0.05:
    print("We reject the null hypothesis saying that there is a significant relationship between smoker and sex.")
else:
    print("We do not reject the null hypothesis saying that there is no significant relationship between smoker and sex.")

We do not reject the null hypothesis saying that there is no significant relationship between smoker and sex


## ----------------------------------------------------------------------------------------------------------------------

## 2. T - test
* 1 sample t test
* 2 sample t test
* Paired test
* 3 sample test - ANOVA

### 1 Sample t test

In [37]:
ages = [20,25,30,35,20,19,20,25,27,28,40,35,40,20,23,26,27,28,29,30,31,33,36,21,22]
len(ages)

25

In [40]:
round(np.mean(ages)) # Average age of the entire population

28.0

In [44]:
randam_selection = np.random.choice(ages,size=5)
randam_selection

array([27, 25, 20, 30, 25])

In [45]:
from scipy.stats import ttest_1samp # to perform one sample t test

In [47]:
t_value, pval = ttest_1samp(randam_selection,28)

In [48]:
if pval<0.05:
    print("We reject the null hypothesis saying that there is a significant difference between average age of pop and samp")
else:
    print("We do not reject the null hypothesis saying that there is no significant difference between average age of pop and sample")

We do not reject the null hypothesis saying that there is no significant difference between average age of pop and sample


#### 2 Sample t test

In [49]:
from scipy.stats import ttest_ind

In [53]:
#Sangeeta
hostelers=[80,60,70,90,40,50,60,80]
day_borders=[40,50,80,60,60,50,70,80]
statistics,pvalue=ttest_ind(hostelers,day_borders)
print("statistics {} \n pvalue is {}".format(statistics,pvalue))

if (pvalue < 0.05):
    print("null hypothesis will be rejected")
else:
    print("null hypothesis will not be rejected")


statistics 0.6347264748233893 
 pvalue is 0.5358425325708169
null hypothesis will not be rejected


In [51]:
#Manju Kiran
farm_a=[100,120,95,90,105,110,99,92,119,112]
farm_b=[90,98,82,73,110,120,118,120,100,90]
ttest_ind(farm_a,farm_b)

if pval<0.05:
    print("We reject the null hypothesis saying there is a significant difference in weight(gms) b/w Apples from Farm A compared to Farm B")
else:
    print("We do not reject the null hypothesis saying that there is no ignificant difference in weight(gms) b/w Apples from Farm A compared to Farm B")


We do not reject the null hypothesis saying that there is no ignificant difference in weight(gms) b/w Apples from Farm A compared to Farm B


In [54]:
#Dhanashree
from scipy.stats import ttest_ind
vaccine1= pd.Series([20,30,40,50,70])
vaccine2=pd.Series([100,120,150,200,115])
statistic,pval =ttest_ind(vaccine1,vaccine2)
print('Statistic value is {} and pval is {}'.format(statistic,pval))
#HO: no significant change in vaccine1 people from vaccine 2
#Ha: there is significant change in vaccine 1 people from vaccine 2

#INFERENCE: VACCINE1 IS EFFECTIVE THAN VACCINE 2

Statistic value is -4.822894284384691 and pval is 0.0013164978992511245


In [56]:
#Rooba
cement_str=[20,30,25,35,40,45,37,34,56,47]
flyash_str=[10,21,15,17,14,17,19,9,10,14]
mean_cement_str=np.mean(cement_str)
mean_flyash_str=np.mean(flyash_str)
statistic,pvalue=ttest_ind(cement_str,flyash_str)
print('statistics is {}\n pvalue is {}'.format(statistic,pvalue))

if pvalue<0.05:
    print('There is significant difference in strength produced by them')
else:
    print('The average strength produced by fly-ash is same as that of cement')

if mean_cement_str>mean_flyash_str:
    print('cement produced more strenght')
else:
    print('flyash have more strenght')

statistics is 6.170946051643655
 pvalue is 7.95610232719977e-06
There is significant difference in strength produced by them
cement produced more strenght


#### Paired t test

In [57]:
from scipy.stats import ttest_rel

In [ ]:
ttest_rel()

In [58]:
#Darshan - Paired test
weight_preworkout = [89,85,35,95,79,82,99,88,101,72,84,86,92]
weight_postworkout = [55,62,65,56,42,46,68,52,70,60,55,51,69]
statistics,pval = ttest_rel(weight_preworkout,weight_postworkout)
print("Statistics is {} \n pvalue is {}".format(statistics,pval))
if pval < 0.05:
    print("We reject null hypothesis saying that there is a significant relationship between average weight before and after ")
else:
    print("We do not reject null hypothesis saying that there is no significant relationship between average weight before and after")

# INFERENCE: There is chnage in weight of people 
#NH: No change
#AH: There is change in weight

Statistics is 5.07655590683381 
 pvalue is 0.0002722070875643695
We reject null hypothesis saying that there is a significant relationship between average weight before and after 


## ANOVA - more than 2 sample t test

In [59]:
from scipy.stats import f_oneway

In [ ]:
# f_oneway()

In [60]:
#H0
#Ha

#Data Collection
rainfall_2018=[32,41,20,21,22,27,26,37,40,41,42,40]
rainfall_2019=[40,30,20,22,32,37,24,29,30,32,41,41]
rainfall_2020=[30,20,45,44,47,21,20,19,20,21,42,42]
statistic,pvalue=f_oneway(rainfall_2018,rainfall_2019,rainfall_2020)
print('statistics is {}\n pvalue is {}'.format(statistic,pvalue))
if pvalue<0.05:
    print('Tamilnadu recieves different amouth of rainfall') #Ha
else:
    print('Tamilnadu recieves uniform amount of rainfall') #Ho
    
# 12 month rainfall data is collected for 3 years
# Here null hypothesis is accepted 
# inference tamilnadu recieves unifrom amount of rainfall


statistics is 0.07590657652120467
 pvalue is 0.9270641538661927
Tamilnadu recieves uniform amount of rainfall


In [61]:
#Manju Kiran
school_a=[100,98,95,90,89]
school_b=[99,98,96,35,75]
school_c=[70,55,98,92,89]
f_stat,pval=f_oneway(school_a,school_b,school_c)
print("The f-stat is {} and pval is {}".format(f_stat,pval))

if pval<0.05:
    print("We reject the null hypothesis saying there is a significant difference in scores b/w the Students from School A,B and C")
else:
    print("We do not reject the null hypothesis saying that there is no significant difference in scores b/w the Students from School A,B and C")


The f-stat is 0.8624460167233299 and pval is 0.4467184149873274
We do not reject the null hypothesis saying that there is no significant difference in scores b/w the Students from School A,B and C


In [62]:
normalcdf(lower limit, upper limit, 0, 1)#Sangeeta
hun_mt=[50,40,60,50]
two_hun_mt=[60,50,60,55]
marathon=[40,50,60,35]
statistic,pvalue=f_oneway(hun_mt,two_hun_mt,marathon)
print("Statistics {}\n Pvalue {}".format(statistic,pvalue))
if (pvalue<0.05):
    print("Runners have significance of weight ")
else:
    print("Runners don't have significance of weight ")


Statistics 1.4411764705882355
 Pvalue 0.2864377648612401
Runners don't have significance of weight 


In [ ]:
hun_mt=[50,40,60,50]
two_hun_mt=[60,50,60,55]
marathon=[40,50,60,35]
statistic,pvalue=f_oneway(hun_mt,two_hun_mt,marathon)
print("Statistics {}\n Pvalue {}".format(statistic,pvalue))
if (pvalue<0.05):
    print("Runners have significance of weight ")
else:
    print("Runners don't have significance of weight ")


## 1 Sample proportion test

In [ ]:
normalcdf(lower limit, upper limit, 0, 1)

In [37]:
ages = [20,25,30,35,20,19,20,25,27,28,40,35,40,20,23,26,27,28,29,30,31,33,36,21,22]
len(ages)

25

In [40]:
round(np.mean(ages)) # Average age of the entire population

28.0

In [44]:
randam_selection = np.random.choice(ages,size=5)
randam_selection

array([27, 25, 20, 30, 25])

In [45]:
from scipy.stats import ttest_1samp # to perform one sample t test

In [47]:
t_value, pval = ttest_1samp(randam_selection,28)

In [48]:
if pval<0.05:
    print("We reject the null hypothesis saying that there is a significant difference between average age of pop and samp")
else:
    print("We do not reject the null hypothesis saying that there is no significant difference between average age of pop and sample")

We do not reject the null hypothesis saying that there is no significant difference between average age of pop and sample


## 2 Sample proportion test

In [4]:
import numpy as np
import statsmodels.stats.proportion as a

## Chi-squared test

In [1]:
# Example of the Chi-Squared Test
from scipy.stats import chi2_contingency
table = [[10, 20, 30],[6,  9,  17]]
stat, p, dof, expected = chi2_contingency(table)
print('stat=%.3f, p=%.3f' % (stat, p))
if p > 0.05:
	print('Probably independent')
else:
	print('Probably dependent')

stat=0.272, p=0.873
Probably independent
