## Framework>Libraries>Package>Modules>Functions>keywords>methods>argument>parameter/expression

* Rows-observations
* Column-parameters/features

* attributes-without ()
* method/func- with ()

In [2]:
%config Completer.use_jedi = False
# c.IPCompleter.use_jedi = False
# These commands are to make notebook suggestions faster

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
!pip install jupyter_contrib_nbextensions
!jupyter contrib nbextension install --user
!jupyter nbextension enable varInspector/main
!jupyter nbextension enable spellchecker/main
!jupyter nbextension enable codefolding/main

In [3]:
2**3

8

In [4]:
pow(2,3)

8

In [5]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [6]:
pow(2,3)
2**3
#use % to get a remainder
#use// to get a whole number after division

8

In [7]:
print(2**3)
print(pow(2,3))
#use print to print 2 or more commands at once

8
8


In [8]:
dir(__builtins__)
#use this to see all the built in functions available in Python, dir- directory, builtin- Its a Module

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [9]:
import builtins

In [10]:
builtins
#in python module are inactive/passive by default so with import we activate/initialize them

<module 'builtins' (built-in)>

In [2]:
import pandas as pd
pd.read_csv?

In [11]:
help(__builtins__)

Help on built-in module builtins:

NAME
    builtins - Built-in functions, exceptions, and other objects.

DESCRIPTION
    Noteworthy: None is the `nil' object; Ellipsis represents `...' in slices.

CLASSES
    object
        BaseException
            Exception
                ArithmeticError
                    FloatingPointError
                    OverflowError
                    ZeroDivisionError
                AssertionError
                AttributeError
                BufferError
                EOFError
                ImportError
                    ModuleNotFoundError
                LookupError
                    IndexError
                    KeyError
                MemoryError
                NameError
                    UnboundLocalError
                OSError
                    BlockingIOError
                    ChildProcessError
                    ConnectionError
                        BrokenPipeError
                        ConnectionAbortedError
           

In [12]:
help(builtins)

Help on built-in module builtins:

NAME
    builtins - Built-in functions, exceptions, and other objects.

DESCRIPTION
    Noteworthy: None is the `nil' object; Ellipsis represents `...' in slices.

CLASSES
    object
        BaseException
            Exception
                ArithmeticError
                    FloatingPointError
                    OverflowError
                    ZeroDivisionError
                AssertionError
                AttributeError
                BufferError
                EOFError
                ImportError
                    ModuleNotFoundError
                LookupError
                    IndexError
                    KeyError
                MemoryError
                NameError
                    UnboundLocalError
                OSError
                    BlockingIOError
                    ChildProcessError
                    ConnectionError
                        BrokenPipeError
                        ConnectionAbortedError
           

In [13]:
import math

In [14]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [7]:
!cd

C:\Users\manan


In [5]:
!dir

 Volume in drive C is OS
 Volume Serial Number is 5A7A-E98D

 Directory of C:\Users\manan\Excelr\Python

01-08-2021  14:56    <DIR>          .
01-08-2021  14:56    <DIR>          ..
15-07-2021  22:07    <DIR>          .ipynb_checkpoints
17-07-2021  13:57                46 abcd.txt
24-07-2021  15:38             3,629 AirPassengers.csv
10-07-2021  12:23           473,848 Assignment operators.PNG
31-07-2021  19:18           267,076 chart1.PNG
31-07-2021  19:19           284,452 chart2.PNG
31-07-2021  19:20           331,626 chart3.PNG
31-07-2021  19:55           254,001 chart4.PNG
31-07-2021  19:55           314,519 chart5.PNG
31-07-2021  19:57           267,065 chart6.PNG
31-07-2021  19:58           276,998 chart7.PNG
31-07-2021  20:01           353,469 chart8.PNG
01-08-2021  00:39           275,174 correlation.PNG
24-07-2021  15:41             6,183 GDP.xlsx
24-07-2021  17:38           314,440 General codes.PNG
10-07-2021  12:31           371,967 Logical operators.PNG
31-07-2021  20:48 

In [15]:
math

<module 'math' (built-in)>

In [16]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    comb(n, k, /)
        Number of ways to choose k items from n items without repetition and without order

## we use !pip when we need to send command through cmd
* usually when python is installed manually 
* with anaconda it should be fine but when using multipe pip installs in a single cell use this !

In [1]:
pip --version

pip 21.0.1 from C:\Users\manan\anaconda3\lib\site-packages\pip (python 3.8)

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip freeze>C:\Users\manan\Desktop\pip.txt
# pip install -r C:\Users\manan\Desktop\pip.txt 
# use first command to import all installed pip packages on destokp in a text file
# use 2nd line to shift all pip packages from one pc to another this will install all pip packages from the txt file in one go

In [2]:
pip freeze

alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client==1.7.2
anaconda-navigator==2.0.3
anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1610472525955/work
anyio @ file:///C:/ci/anyio_1620153418380/work/dist
appdirs==1.4.4
argh==0.26.2
argon2-cffi @ file:///C:/ci/argon2-cffi_1613037959010/work
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///C:/ci/astroid_1613501047216/work
astropy @ file:///C:/ci/astropy_1617745647203/work
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1615918855173/work
Babel @ file:///tmp/build/80754af9/babel_1607110387436/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work
backports.shutil-get-terminal-

In [17]:
math.sqrt(2)
#to use squareroot func within the math module

1.4142135623730951

In [18]:
math.pow(2,3)
#some functions are repeated within different modules to save resources by not running different modules 
#i.e avoiding cross module usage
#difference in normal pow and math.pow is that this one gives float value,this one accept only 2 arguments 
#unlike pow which uses 3

8.0

### To download package from pypi.org

In [19]:
pip install bs4

Note: you may need to restart the kernel to use updated packages.


In [20]:
var1=1
var2=2
sum=var1+var2
print(sum)

3


In [21]:
type(var1)

int

## There are some predefined keywords which cant be used as variables

In [22]:
a=input("Enter the Value")

Enter the Value1


In [23]:
a

'1'

### OR

In [24]:
print(a)

1


In [25]:
type(a)
#it took it as a string by default as type wasnt mentioned

str

In [26]:
b=int(input("Enter the Value"))
#here we declared that value should be integer

Enter the Value1


In [27]:
print(b)

1


In [28]:
b

1

In [29]:
type(b)

int

In [30]:
x=int(input("Enter 1st number"))
y=int(input("Enter 2nd number"))
z=int(input("Enter 3rd number"))
print("Max number is:")
print(max(x,y,z))

#OR
#print("Max number is:",max(x,y,z))

Enter 1st number2
Enter 2nd number3
Enter 3rd number5
Max number is:
5


## Assignment Operators

In [31]:
x=4
x=x+5
x

9

### OR

In [32]:
x=4
x+=5
x

9

In [33]:
# x+=5,x-=5,x/=5   and  so on

### Comparison Operators


In [34]:
# <,> ,==, !=

###  Logical Operators


In [35]:
# and, or , not

### Bitwise Operators

In [ ]:
# a|b -Or , a&b  -And  ,a^b  -Xor, like binary numbers used by app deve lopers

### Identity Operators

In [140]:
# is/is not

### Membership Operators

In [ ]:
# Same like Identity operators, these are just used with list

## List

In [100]:
a=['1','2','3']
a

['1', '2', '3']

In [102]:
a.append('4')
a

['1', '2', '3', '4']

In [103]:
a.remove('4')
a

['1', '2', '3']

In [39]:
b=[4,8,12]
b

[4, 8, 12]

In [40]:
a.extend(b) #using a+b does the same however it does that only in the runtime i.e actual value when printing a won't change
a
# meaning of runtime is that we can see the added value of a+b, but when we print a,b separately it will show old values
#  while with a.extend(b) the value of a will be changed and will have a+b value

['1', '2', '3', 4, 8, 12]

In [41]:
a[0:2]
# n:n-1

['1', '2']

In [42]:
a[-1]

12

In [43]:
a[-3:]

[4, 8, 12]

In [97]:
#    index,value
a.insert(2,'h')
a

['1', '2', 'h', 'h']

In [99]:
a.pop(2)
# Use index number
#it shows removed value, by default last value is removed if index number isn't entered i.e value is left empty

'h'

In [44]:
stri='Python'
stri

'Python'

In [45]:
stri[2:7]

'thon'

In [46]:
stri[-1]+stri[2]

'nt'

In [55]:
stri.find('thon')
#start position of this pattern

2

In [48]:
stri.replace('Py','p')

'pthon'

In [49]:
stri.split(',')

['Python']

# ________

In [50]:
strin='P,y,t,h,o,n'
strin

'P,y,t,h,o,n'

In [71]:
strin.split(',')
#basically splits every wrod/letter after a comma

['P', 'y', 't', 'h', 'o', 'n']

# _______

In [63]:
stri.count('o',2,6)
#          str,from,to

1

In [1]:
help(str.count)

Help on method_descriptor:

count(...)
    S.count(sub[, start[, end]]) -> int
    
    Return the number of non-overlapping occurrences of substring sub in
    string S[start:end].  Optional arguments start and end are
    interpreted as in slice notation.



In [64]:
stri.upper()
# lower

'PYTHON'

In [65]:
max(stri)
# min

'y'

In [70]:
stri.isalpha()
#to check if values are alphabets only

True

In [104]:
# Tuple is used with (), only difference in tuple and list is that tuple is immutable i.e can't be changed

## Dictionaries

In [116]:
myDict1={1:'Apple',2:'Mango',3:'Ball'}
# dictionary with int

In [117]:
myDict2={'Name':'Manan',1:[2,3,4]}
# dictionary with mixed keys

In [115]:
myDict3=dict([(1,'Apple'),(2,'Banana')])
# dictionary with sequence having each item as pair

In [136]:
myDict1[1]

'Apple'

In [119]:
len(myDict1)

3

In [121]:
myDict1.keys()

dict_keys([1, 2, 3])

In [122]:
myDict1.values()

dict_values(['Apple', 'Mango', 'Ball'])

In [123]:
myDict1.items()

dict_items([(1, 'Apple'), (2, 'Mango'), (3, 'Ball')])

In [139]:
myDict1.get(1)

'Apple'

In [127]:
myDict1.update({4:'Hello'})
myDict1

{1: 'Apple', 2: 'Mango', 3: 'Ball', 4: 'Hello'}

In [129]:
myDict1.pop(4)

'Hello'

In [130]:
myDict1

{1: 'Apple', 2: 'Mango', 3: 'Ball'}

## Sets

In [133]:
# sets are used with {}, they cannot have repetetive values
# var1|var2  used for union          removed repetetive elements
# var1&var2  used for intersection   shows repetetive elements

In [9]:
n= float(input("Number ?"))
if n>=0:
    print("The absolute value of ",n, " is ", n)
else:
    print("The absolute value of ",n, " is ", -n)
sumofnum=50+60
print(sumofnum)

Number ?-1
The absolute value of  -1.0  is  1.0
110


In [10]:
n= float(input("Number ?"))
if n>=0:
    print("The absolute value of ",n, " is ", n)
else:
    print("The absolute value of ",n, " is ", -n)
    sumofnum=50+60
    print(sumofnum)
#  adding space/indentation in last 2 lines will make the statements execute in else statement

Number ?1
The absolute value of  1.0  is  1.0


In [15]:
name=  input("Enter your name:")
print(name)
if name=="kiran":
    print("The name entered is",name)
elif name=="john":
    print("The name entered is",name)
elif name=="tim":
    print("The name entered is",name)
else:
    print("The name entered is incorrect")

Enter your name:john
john
Thne name entered is john


# Nested IF

In [4]:
name="animals"
animalname="4dog"
if name=="animals":
    if animalname=="2dog":
        print("Valid Animal")
        print("Name entered is Animal")
    else:
        print("i have given up")
        print("abc")
else:
    print("the name entered is not valid")

i have given up
abc


In [7]:
a=0
while a<5:
    print("First:",a)
    a=a+1
    print("Second:",a)

First: 0
Second: 1
First: 1
Second: 2
First: 2
Second: 3
First: 3
Second: 4
First: 4
Second: 5


In [8]:
a=1
s=0
print("Enter no. to add the sum:")
print("Enter 0 to exit the loop")
while a!=0:
    print("Current sum:",s)
    a=float(input("Enter the number:"))
    s=s+a
print("The total sum:",s)    

Enter no. to add the sum:
Enter 0 to exit the loop
Current sum: 0
Enter the number:2
Current sum: 2.0
Enter the number:0
The total sum: 2.0


In [9]:
import random
target_num,guess_num=random.randint(1,10),0
#print(target_num,"Target")
#print(gurss_num,"Guess")
while target_num!=guess_num:
    guess_num=int(input("Guess the no bw 1-10 untill its correct"))
print("Well Guessed")    

Guess the no bw 1-10 untill its correct1
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct10
Guess the no bw 1-10 untill its correct2
Guess the no bw 1-10 untill its correct10
Guess the no bw 1-10 untill its correct3
Well Guessed


In [4]:
lis=[0,1,2,3,4,5,6]
for index in range(0,len(lis)):
    lis[index]=lis[index]+2
print(lis)

[2, 3, 4, 5, 6, 7, 8]


In [5]:
lis=[]
example="Hello"
for char in example:
    lis.append(char)
print(lis)
print([char for char in example])

['H', 'e', 'l', 'l', 'o']
['H', 'e', 'l', 'l', 'o']


In [9]:
int_list=[1,3,4,8,6,5]
[integer for integer in int_list if integer%2==0]

[4, 8, 6]

In [10]:
["Even" if integer%2==0 else "Odd" for integer in int_list]

['Odd', 'Odd', 'Even', 'Even', 'Even', 'Odd']

In [32]:
import datetime as dt
var=dt.datetime.now()
print(var)

2021-07-17 13:07:18.506706


In [33]:
var

datetime.datetime(2021, 7, 17, 13, 7, 18, 506706)

In [35]:
from datetime import time
a=time()
print("a=",a)
b=time(11,34,56)
print("b=",b)
c=time(hour=11,minute=34,second=56)
print("c=",c)
d=time(11,34,56,234566)
print("d=",d)

a= 00:00:00
b= 11:34:56
c= 11:34:56
d= 11:34:56.234566


In [39]:
from datetime import time,datetime
t1=datetime(2020,8,15,12,5,8,34)
t2=datetime(2010,7,5,17,4,4,13)
t3=t1-t2
print(t3)
t3

3693 days, 19:01:04.000021


datetime.timedelta(days=3693, seconds=68464, microseconds=21)

In [58]:
now=datetime.now()
datetime.strftime(now,"%Y/ %m- %d   %H %M %S   %B")

'2021/ 07- 17   13 40 54   July'

## Asyncronous (like /NEFT transfer that happen each hour)

In [69]:
fh= open("abcd.txt","w")  #this will create a file abcd where your .ipynp is or "C:\\Users\\manan\\Excelr\\Python\\abcd.txt add path , w is write parameter
fh.writelines("this is line no.1")
fh.writelines("             ")
fh.writelines("this is line no.")
fh.close()

In [74]:
fh= open("abcd.txt","r")
print(fh.read())
fh.close()

this is line no.1             this is line no.


In [61]:
print(fh)

<_io.TextIOWrapper name='abcd.txt' mode='w' encoding='cp1252'>


In [75]:
# w=write and create file
# r=read
# w+=read,write and create
# r+=read and write
# a=append

## web scrapping and web crawling

In [92]:
!pip install bs4
!pip install lxml

  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1273 sha256=080303a6ff355c4016742900565985a67e6f9ce70c486cd53fb9d4d8928b73a1
  Stored in directory: c:\users\manan\appdata\local\pip\cache\wheels\75\78\21\68b124549c9bdc94f822c02fb9aa3578a669843f9767776bca
Successfully built bs4


In [93]:
!pip install lxml

In [97]:
import bs4 as bs
import urllib.request
sauce=urllib.request.urlopen("https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html#").read()
soup=bs.BeautifulSoup(sauce,"lxml") #we use lxml as data processing is faster in it
#print(sauce)
#print(soup)
print(soup.title)

<title>10 minutes to pandas — pandas 1.3.0 documentation</title>


## lambda
used as a undefined function

In [95]:
double=lambda x: x*2
# x is a argument here and later we multiply x with 2

In [96]:
double(4)

8

In [100]:
my_list=[1,2,3,4,5,6]
new_list=list(filter(lambda x:(x%2==0),my_list))
new_list

[2, 4, 6]

In [103]:
my_list=[1,2,3,4,5,6]
new_list=list(map(lambda x:x%2==0,my_list))
new_list

[False, True, False, True, False, True]

In [104]:
my_list=[1,2,3,4,5,6]
new_list=list(map(lambda x:x*2,my_list))
new_list

[2, 4, 6, 8, 10, 12]

## Regular Expression

In [116]:
import re

NameAge='''
Ashu is 23 and Manan is 26
Raju is 45 and Tom is 101 and Ron is 1024'''
ages=re.findall(r'\d{1,3}',NameAge) #1,3 a=is the range of digits
names=re.findall(r'[A-Z][a-z]*',NameAge) # [A-Z] means words should start with capital letters,[a-z] for small and * to make it continuous
print(ages)
print(names)

ageDict={}
x=0
for eachname in names:
    ageDict[eachname]=ages[x]
    x+=1
print(ageDict)

['23', '26', '45', '101', '102', '4']
['Ashu', 'Manan', 'Raju', 'Tom', 'Ron']
{'Ashu': '23', 'Manan': '26', 'Raju': '45', 'Tom': '101', 'Ron': '102'}


In [6]:
import re
email="skoal.com abc@com 123@abx.ty.com2 Manan.5587@gmail.com   abc@bhe.com"
# print("Email Matches",(re.findall("[\w._%+-]{1,20}@[\w.-]{2,20}.[A-Za-z]{2,3}",email)))
print("Email Matches",len(re.findall("[\w._%+-]{1,20}@[\w.-]{2,20}.[A-Za-z]{2,3}",email)))

Email Matches 3


In [143]:
help(re)

Help on module re:

NAME
    re - Support for regular expressions (RE).

MODULE REFERENCE
    https://docs.python.org/3.8/library/re
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides regular expression matching operations similar to
    those found in Perl.  It supports both 8-bit and Unicode strings; both
    the pattern and the strings being processed can contain null bytes and
    characters outside the US ASCII range.
    
    Regular expressions can contain both special and ordinary characters.
    Most ordinary characters, like "A", "a", or "0", are the simplest
    regular expressions; they simply match themselves.  You can
    concatenate ordinary characters, so last mat

In [2]:
import re
phone="212-544-1547"
if re.search(r"\d{3}-\d{3}-\d{4}",phone):
    print("Its a valid number")
else:
    print("Its not a valid number")

Its a valid number


In [9]:
import urllib.request
from re import findall
url="https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html#"

response=urllib.request.urlopen(url)
html=response.read()
htmlstr=html.decode()

pdata=findall("\(\d{3}\) \d{3}-\d{4}",htmlstr)

for items in pdata:
    print(items)

#     this code is to find (000)000-0000 numbers in this format on a website

# Numpy

In [8]:
import numpy as np
a=np.array(([1,2,3],[4,5,6])) # array works like matrix form
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
import numpy
import time
import sys # for using as OS level like calculation cpu, memory usage
s=range(1000)
# print(s)
# print(len(s))
print("Memory usage in procedural approach",sys.getsizeof(10)*len(s))
print(sys.getsizeof(10))
d=numpy.arange(1000) #its a-range/
# print(d)
print(d.size)
print(d.itemsize)
print("Memory usage in numpy approach",d.itemsize*d.size)

Memory usage in procedural approach 28000
28
1000
4
Memory usage in numpy approach 4000


In [2]:
import numpy as np
a=np.array(([1,2,3],[4,5,6]))
print(a)
print("\n",a.shape)
a=a.reshape(3,2)
print("\n",a)

[[1 2 3]
 [4 5 6]]

 (2, 3)

 [[1 2]
 [3 4]
 [5 6]]


In [10]:
a=np.array([(1,2,3),(4,5,6)])
print(a,"\n")
print(a.shape,"\n")
print("Max",a.max())
print("Min",a.min())
print("Sum",a.sum())
print("Column sum",a.sum(axis=0))
print("Row sum",a.sum(axis=1))

[[1 2 3]
 [4 5 6]] 

(2, 3) 

Max 6
Min 1
Sum 21
Column sum [5 7 9]
Row sum [ 6 15]


In [16]:
a=np.array([(1,2,3,4),(5,4,8,7),(1,5,7,9)])
b=np.array([(1,2,3,4),(5,4,8,7),(1,5,7,9)])
print(a,"\n\n",b)

[[1 2 3 4]
 [5 4 8 7]
 [1 5 7 9]] 

 [[1 2 3 4]
 [5 4 8 7]
 [1 5 7 9]]


In [17]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.         2.82842712 2.64575131]
 [1.         2.23606798 2.64575131 3.        ]]


## Math

In [19]:
import math

In [20]:
# Stacking
print(np.shape(a))
print(np.shape(b))

print(np.hstack((a,b))) #horizontal stacking
print(np.hstack((a,b)).shape)

(3, 4)
(3, 4)
[[1 2 3 4 1 2 3 4]
 [5 4 8 7 5 4 8 7]
 [1 5 7 9 1 5 7 9]]
(3, 8)


In [21]:
# Stacking
print(np.shape(a))
print(np.shape(b))

print(np.vstack((a,b))) #Vertical stacking
print(np.vstack((a,b)).shape)

(3, 4)
(3, 4)
[[1 2 3 4]
 [5 4 8 7]
 [1 5 7 9]
 [1 2 3 4]
 [5 4 8 7]
 [1 5 7 9]]
(6, 4)


In [36]:
import numpy as np
a=np.arange(10)
print(a)
s=slice(2,7,2)
print(a[s])
# print(s)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [40]:
import numpy as np
a=np.arange(10)
print(a.shape)
print(a)
b=a[2:7:2]
print(b)

(10,)
[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


# df[df] -dataframe within dataframe

In [40]:
import pandas as pd
df=pd.read_csv("sfo.csv")
df

day  temperature  windspeed  event
0   01-01-2018         32.5          5   rain
1   01-02-2018         31.8          6  sunny
2   01-03-2018         34.0          7  windy
3   01-04-2018         33.0          4   rain
4   01-05-2018         32.0          5  sunny
5   01-06-2018         33.0          7  windy
6   01-07-2018         32.0          6   rain
7   01-08-2018         32.0          5  sunny
8   01-09-2018         34.0          4  windy
9   01-10-2018         23.0          3   rain
10  01-11-2018         24.0          4  sunny
11  01-12-2018         25.0          5  windy
12  01/13/2018         26.0          7   rain
13  01/14/2018         27.0          7  sunny

In [38]:
df=df[df["temperature"]==df["temperature"].max()]
df

day  temperature  windspeed  event
2  01-03-2018         34.0          7  windy
8  01-09-2018         34.0          4  windy

In [35]:
df=df["temperature"]==df["temperature"].max()  # and or == these give boolean value by default
print(df[df],"\n")
print(df)

2    True
8    True
Name: temperature, dtype: bool 

0     False
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
Name: temperature, dtype: bool


In [41]:
df.set_index("day",inplace=True)
df

temperature  windspeed  event
day                                      
01-01-2018         32.5          5   rain
01-02-2018         31.8          6  sunny
01-03-2018         34.0          7  windy
01-04-2018         33.0          4   rain
01-05-2018         32.0          5  sunny
01-06-2018         33.0          7  windy
01-07-2018         32.0          6   rain
01-08-2018         32.0          5  sunny
01-09-2018         34.0          4  windy
01-10-2018         23.0          3   rain
01-11-2018         24.0          4  sunny
01-12-2018         25.0          5  windy
01/13/2018         26.0          7   rain
01/14/2018         27.0          7  sunny

In [42]:
df.columns

Index(['temperature', 'windspeed', 'event'], dtype='object')

In [43]:
df.shape

(14, 3)

In [45]:
df.reset_index(inplace=True)

In [46]:
df.shape

(14, 4)

In [47]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

##  To Read Self made data

In [48]:
# For Dictionary
import pandas as pd
weather_data= {"day":["01-12-2018","01-11-2018","01-10-2018"],"temperature":["10","20","30"]}

In [50]:
df=pd.DataFrame(weather_data)  
df

day temperature
0  01-12-2018          10
1  01-11-2018          20
2  01-10-2018          30

In [59]:
# For Tuple/List
import pandas as pd
weather_data= [("01-12-2018","10"),("01-11-2018","20")]

In [60]:
df=pd.DataFrame(weather_data,columns=["day","temperature"])  
df

day temperature
0  01-12-2018          10
1  01-11-2018          20

In [62]:
data=pd.read_excel("World Bank Indicators.xlsx")

In [63]:
data.head()

Country Name       Date  Transit: Railways, (million passenger-km)  \
0  Afghanistan 2000-07-01                                        0.0   
1  Afghanistan 2001-07-01                                        0.0   
2  Afghanistan 2002-07-01                                        0.0   
3  Afghanistan 2003-07-01                                        0.0   
4  Afghanistan 2004-07-01                                        0.0   

   Transit: Passenger cars (per 1,000 people)  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                         NaN   
4                                         NaN   

   Business: Mobile phone subscribers  \
0                                 0.0   
1                                 0.0   
2                             25000.0   
3                            200000.0   
4                            600000.0   

   Business: Internet users (per 100 people)  \
0                                        NaN   
1                                        0.0   
2                                        0.0   
3                                        0.0   
4                                        0.0   

   Health: Mortality, under-5 (per 1,000 live births)  \
0                                              151.0    
1                                              150.0    
2                                              150.0    
3                                              151.0    
4                                              150.0    

   Health: Health expenditure per capita (current US$)  \
0                                               11.0     
1                                               11.0     
2                                               22.0     
3                                               25.0     
4                                               30.0     

   Health: Health expenditure, total (% GDP)  Population: Total (count)  \
0                                        8.0                   25950816   
1                                        9.0                   26697430   
2                                        7.0                   27465525   
3                                        8.0                   28255719   
4                                        9.0                   29068646   

   Population: Urban (count)  Population:: Birth rate, crude (per 1,000)  \
0                  5527524.0                                        51.0   
1                  5771984.0                                        50.0   
2                  6025936.0                                        49.0   
3                  6289723.0                                        48.0   
4                  6563700.0                                        47.0   

   Health: Life expectancy at birth, female (years)  \
0                                              45.0   
1                                              46.0   
2                                              46.0   
3                                              46.0   
4                                              46.0   

   Health: Life expectancy at birth, male (years)  \
0                                            45.0   
1                                            45.0   
2                                            46.0   
3                                            46.0   
4                                            46.0   

   Health: Life expectancy at birth, total (years)  \
0                                             45.0   
1                                             46.0   
2                                             46.0   
3                                             46.0   
4                                             46.0   

   Population: Ages 0-14 (% of total)  Population: Ages 15-64 (% of total)  \
0                                48.0                                 50.0   
1      

In [75]:
data.columns.values

array(['Country Name', 'Date',
       'Transit: Railways, (million passenger-km)',
       'Transit: Passenger cars (per 1,000 people)',
       'Business: Mobile phone subscribers',
       'Business: Internet users (per 100 people)',
       'Health: Mortality, under-5 (per 1,000 live births)',
       'Health: Health expenditure per capita (current US$)',
       'Health: Health expenditure, total (% GDP)',
       'Population: Total (count)', 'Population: Urban (count)',
       'Population:: Birth rate, crude (per 1,000)',
       'Health: Life expectancy at birth, female (years)',
       'Health: Life expectancy at birth, male (years)',
       'Health: Life expectancy at birth, total (years)',
       'Population: Ages 0-14 (% of total)',
       'Population: Ages 15-64 (% of total)',
       'Population: Ages 65+ (% of total)', 'Finance: GDP (current US$)',
       'Finance: GDP per capita (current US$)'], dtype=object)

In [76]:
data.columns

Index(['Country Name', 'Date', 'Transit: Railways, (million passenger-km)',
       'Transit: Passenger cars (per 1,000 people)',
       'Business: Mobile phone subscribers',
       'Business: Internet users (per 100 people)',
       'Health: Mortality, under-5 (per 1,000 live births)',
       'Health: Health expenditure per capita (current US$)',
       'Health: Health expenditure, total (% GDP)',
       'Population: Total (count)', 'Population: Urban (count)',
       'Population:: Birth rate, crude (per 1,000)',
       'Health: Life expectancy at birth, female (years)',
       'Health: Life expectancy at birth, male (years)',
       'Health: Life expectancy at birth, total (years)',
       'Population: Ages 0-14 (% of total)',
       'Population: Ages 15-64 (% of total)',
       'Population: Ages 65+ (% of total)', 'Finance: GDP (current US$)',
       'Finance: GDP per capita (current US$)'],
      dtype='object')

In [77]:
data.iloc[[2,5,6,9]]

Country Name       Date  Transit: Railways, (million passenger-km)  \
2  Afghanistan 2002-07-01                                        0.0   
5  Afghanistan 2005-07-01                                        0.0   
6  Afghanistan 2006-07-01                                        0.0   
9  Afghanistan 2009-07-01                                        0.0   

   Transit: Passenger cars (per 1,000 people)  \
2                                         NaN   
5                                         NaN   
6                                        11.0   
9                                        21.0   

   Business: Mobile phone subscribers  \
2                             25000.0   
5                           1200000.0   
6                           2520366.0   
9                          12000000.0   

   Business: Internet users (per 100 people)  \
2                                        0.0   
5                                        1.0   
6                                        2.0   
9                                        3.0   

   Health: Mortality, under-5 (per 1,000 live births)  \
2                                              150.0    
5                                              151.0    
6                                              151.0    
9                                              149.0    

   Health: Health expenditure per capita (current US$)  \
2                                               22.0     
5                                               33.0     
6                                               24.0     
9                                               34.0     

   Health: Health expenditure, total (% GDP)  Population: Total (count)  \
2                                        7.0                   27465525   
5                                        9.0                   29904962   
6                                        7.0                   30751661   
9                                        8.0                   33438329   

   Population: Urban (count)  Population:: Birth rate, crude (per 1,000)  \
2                  6025936.0                                        49.0   
5                  6848236.0                                        47.0   
6                  7158987.0                                        46.0   
9                  8165640.0                                        44.0   

   Health: Life expectancy at birth, female (years)  \
2                                              46.0   
5                                              47.0   
6                                              47.0   
9                                              48.0   

   Health: Life expectancy at birth, male (years)  \
2                                            46.0   
5                                            47.0   
6                                            47.0   
9                                            48.0   

   Health: Life expectancy at birth, total (years)  \
2                                             46.0   
5                                             47.0   
6                                             47.0   
9                                             48.0   

   Population: Ages 0-14 (% of total)  Population: Ages 15-64 (% of total)  \
2                                48.0                                 50.0   
5                                48.0                                 50.0   
6                                48.0                                 50.0   
9                                47.0                                 51.0   

   Population: Ages 65+ (% of total)  Finance: GDP (current US$)  \
2                                2.0                4.338908e+09   
5                                2.0                6.814754e+09   
6                                2.0                7.721932e+09   
9                                2.0                1.421367e+10   

   Finance: GDP per capita (current US$)  
2                         

In [80]:
data[["Date","Transit: Passenger cars (per 1,000 people)"]][0:5]

Date  Transit: Passenger cars (per 1,000 people)
0 2000-07-01                                         NaN
1 2001-07-01                                         NaN
2 2002-07-01                                         NaN
3 2003-07-01                                         NaN
4 2004-07-01                                         NaN

In [8]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [4]:
import cv2

In [7]:
img=cv2.imread("blockchain1.jpg",1) # 1 means colored image, 0 b&W
print(img.shape)
cv2.imshow("Legend",img) # image name and read image from above
cv2.waitKey(0) #waitime
cv2.destroyAllWindows() #will keep the code in [*]loading till the windows is closed

(600, 1000, 3)


## face detection


In [8]:
import cv2

# Create a CascadeClassifier Object
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml") #file provided by opensv to identify all face features

# Reading the image as it is
img = cv2.imread("photo.jpg")

# Reading the image as gray scale image
gray_img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY) #cvto color to COLOR_BGR2GRAYis to convert colored image to grayscale

# Search the co-ordintes of the image
faces = face_cascade.detectMultiScale(gray_img, scaleFactor = 1.05,
                                      minNeighbors=5)             #scalefactor dec the shape value by 5%(1.05) till face is found
print(type(faces))
print(faces)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0),3)  # to find face cordinates and (0,255,0) this gives green rectangle 

resized = cv2.resize(img, (int(img.shape[1]/7),int(img.shape[0]/7)))

cv2.imshow("Gray", img)

cv2.waitKey(0)

cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[88 36 92 92]]


## Video Cordinates

In [1]:
import cv2,time

video = cv2.VideoCapture(0) # 0 for inbuilt camera,1 for external
a = 1
while True:
  a = a + 1
  check, frame = video.read()
  print (frame)
  gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
  cv2.imshow('Capturing',gray)
  key = cv2.waitKey(1)
  if key == ord('q'):
       break
print(a) # This will print the number of frames
video.release()
cv2.destroyAllWindows()

[[[ 90 101  99]
  [ 92 102 100]
  [ 94 104 101]
  ...
  [ 25  18  32]
  [ 25  18  32]
  [ 25  18  31]]

 [[ 91 102 100]
  [ 93 103 101]
  [ 94 104 101]
  ...
  [ 25  19  33]
  [ 25  20  32]
  [ 24  19  31]]

 [[ 91 102 100]
  [ 93 103 101]
  [ 94 104 101]
  ...
  [ 23  20  32]
  [ 23  20  31]
  [ 22  19  30]]

 ...

 [[ 48  42  40]
  [ 47  41  39]
  [ 48  41  39]
  ...
  [  7  14  26]
  [  5  14  25]
  [  6  15  26]]

 [[ 50  42  42]
  [ 49  41  41]
  [ 49  40  40]
  ...
  [  6  15  27]
  [  6  15  27]
  [  7  17  28]]

 [[ 48  40  41]
  [ 49  40  41]
  [ 48  39  39]
  ...
  [  5  14  27]
  [  4  13  26]
  [  4  13  26]]]
[[[113 103 103]
  [111 102 101]
  [108 102 100]
  ...
  [  9  16  28]
  [ 13  17  32]
  [ 16  19  34]]

 [[110 101 101]
  [108 100 100]
  [106 101  99]
  ...
  [ 12  19  29]
  [ 13  17  31]
  [ 15  18  33]]

 [[103  97  98]
  [103  98  99]
  [101  99  98]
  ...
  [ 13  19  28]
  [ 14  18  29]
  [ 15  17  30]]

 ...

 [[ 52  37  34]
  [ 52  38  33]
  [ 53  39  34]
  ..

[[[ 75  93 100]
  [ 74  92  99]
  [ 74  92  98]
  ...
  [  8  23  23]
  [ 10  27  24]
  [ 11  28  24]]

 [[ 73  89  96]
  [ 73  89  96]
  [ 73  89  95]
  ...
  [ 10  23  25]
  [ 10  25  24]
  [  9  25  23]]

 [[ 73  86  94]
  [ 73  86  94]
  [ 73  87  93]
  ...
  [ 11  22  28]
  [ 11  23  27]
  [ 10  24  27]]

 ...

 [[ 49  38  34]
  [ 49  38  33]
  [ 49  39  33]
  ...
  [  6  12  30]
  [  7  12  30]
  [  8  12  30]]

 [[ 51  40  36]
  [ 50  39  34]
  [ 49  39  33]
  ...
  [  9  16  35]
  [ 10  16  35]
  [ 11  16  35]]

 [[ 50  39  35]
  [ 49  38  33]
  [ 48  38  32]
  ...
  [ 12  19  38]
  [ 12  18  37]
  [ 11  17  36]]]
[[[88 90 84]
  [89 91 86]
  [92 93 91]
  ...
  [19 20 34]
  [22 21 37]
  [24 23 39]]

 [[82 85 80]
  [84 86 83]
  [88 89 89]
  ...
  [18 19 34]
  [19 19 35]
  [21 20 37]]

 [[80 84 82]
  [81 85 84]
  [84 87 88]
  ...
  [16 18 34]
  [18 19 37]
  [19 19 38]]

 ...

 [[46 38 39]
  [46 39 40]
  [46 39 39]
  ...
  [ 7 16 27]
  [ 5 16 27]
  [ 4 16 28]]

 [[47 40 41]
  [49 4

[[[76 78 78]
  [78 80 81]
  [79 82 84]
  ...
  [21 36 36]
  [20 36 39]
  [21 38 41]]

 [[78 79 80]
  [79 80 81]
  [79 80 84]
  ...
  [20 34 35]
  [20 35 38]
  [21 37 40]]

 [[81 79 82]
  [80 79 83]
  [80 78 83]
  ...
  [21 34 36]
  [20 34 37]
  [22 35 39]]

 ...

 [[48 38 31]
  [48 38 31]
  [47 37 30]
  ...
  [40 41 55]
  [45 49 64]
  [45 51 67]]

 [[49 39 31]
  [48 38 30]
  [48 38 30]
  ...
  [44 47 62]
  [47 53 69]
  [45 53 69]]

 [[49 40 31]
  [48 39 30]
  [47 38 29]
  ...
  [46 50 66]
  [50 57 73]
  [49 57 74]]]
[[[37 87 77]
  [40 86 77]
  [50 87 81]
  ...
  [38 29 53]
  [41 29 56]
  [42 28 56]]

 [[38 86 77]
  [42 86 79]
  [49 87 81]
  ...
  [33 23 49]
  [38 26 54]
  [37 24 53]]

 [[40 86 80]
  [42 86 80]
  [50 88 83]
  ...
  [30 20 47]
  [37 25 54]
  [35 23 52]]

 ...

 [[54 38 26]
  [54 38 26]
  [53 37 27]
  ...
  [54 54 61]
  [61 61 69]
  [63 62 71]]

 [[51 36 27]
  [51 37 28]
  [51 37 28]
  ...
  [50 50 57]
  [56 56 63]
  [59 58 67]]

 [[47 34 26]
  [48 35 27]
  [49 36 28]
  .

[[[68 75 84]
  [67 73 79]
  [71 75 77]
  ...
  [ 1  6  1]
  [ 4  7  1]
  [ 6  8  2]]

 [[65 72 81]
  [66 72 78]
  [67 71 73]
  ...
  [ 1  6  1]
  [ 2  5  0]
  [ 4  6  0]]

 [[60 67 76]
  [66 72 79]
  [69 74 77]
  ...
  [ 3  8  4]
  [ 5  8  3]
  [ 6  8  3]]

 ...

 [[38 25 23]
  [38 25 23]
  [39 25 23]
  ...
  [ 5  2 15]
  [ 6  2 17]
  [ 8  3 19]]

 [[36 26 23]
  [35 24 22]
  [36 24 22]
  ...
  [ 4  2 15]
  [ 4  1 16]
  [ 6  2 17]]

 [[37 28 25]
  [36 27 24]
  [37 26 24]
  ...
  [ 4  3 16]
  [ 4  2 15]
  [ 5  2 17]]]
[[[66 78 60]
  [71 82 66]
  [71 81 68]
  ...
  [ 5  6 15]
  [ 3  5 12]
  [ 2  5 10]]

 [[64 75 62]
  [64 75 62]
  [64 73 62]
  ...
  [ 4  6 14]
  [ 2  4 11]
  [ 1  4  9]]

 [[63 73 67]
  [64 73 67]
  [64 72 65]
  ...
  [ 3  6 13]
  [ 3  6 11]
  [ 2  5  9]]

 ...

 [[38 27 26]
  [36 26 26]
  [34 25 25]
  ...
  [10  5 37]
  [11  5 39]
  [13  6 40]]

 [[35 25 24]
  [34 24 23]
  [33 24 24]
  ...
  [11  7 38]
  [11  7 39]
  [10  6 39]]

 [[36 27 24]
  [35 27 25]
  [35 26 25]
  .

[[[98 71 91]
  [95 70 90]
  [88 69 88]
  ...
  [ 4  0 40]
  [ 4  0 38]
  [ 3  0 35]]

 [[95 70 87]
  [92 69 86]
  [86 68 84]
  ...
  [ 2  0 37]
  [ 2  0 35]
  [ 2  0 33]]

 [[91 71 81]
  [89 70 80]
  [82 67 78]
  ...
  [ 3  0 34]
  [ 5  0 34]
  [ 5  0 33]]

 ...

 [[37 25 20]
  [37 25 21]
  [39 25 23]
  ...
  [21 16 43]
  [18 15 41]
  [17 15 41]]

 [[35 24 23]
  [36 24 23]
  [37 23 24]
  ...
  [17 13 41]
  [15 13 39]
  [12 11 37]]

 [[34 24 24]
  [35 24 24]
  [38 24 26]
  ...
  [15 12 40]
  [14 13 40]
  [11 10 36]]]
[[[80 81 79]
  [80 79 78]
  [83 78 80]
  ...
  [12 11 14]
  [14 10 18]
  [15 10 19]]

 [[75 75 75]
  [79 77 79]
  [83 78 82]
  ...
  [13 12 16]
  [14 11 17]
  [14 10 18]]

 [[67 67 71]
  [72 70 76]
  [76 71 79]
  ...
  [12 12 16]
  [11 10 16]
  [10  9 16]]

 ...

 [[36 20 24]
  [37 21 25]
  [36 21 25]
  ...
  [14 13 44]
  [14 12 44]
  [14 12 44]]

 [[36 22 24]
  [36 23 25]
  [36 23 25]
  ...
  [13 13 40]
  [13 13 41]
  [13 12 41]]

 [[35 22 24]
  [36 23 25]
  [37 24 26]
  .

[[[64 63 72]
  [63 62 71]
  [63 63 73]
  ...
  [ 0  6  9]
  [ 0  8  8]
  [ 0  8  7]]

 [[62 62 69]
  [64 64 72]
  [66 66 76]
  ...
  [ 0  6 10]
  [ 0  8 10]
  [ 0  7  8]]

 [[67 67 74]
  [66 66 73]
  [67 66 75]
  ...
  [ 0  6 12]
  [ 0  7 11]
  [ 0  7 11]]

 ...

 [[31 16 19]
  [30 17 19]
  [28 17 19]
  ...
  [ 6 10 26]
  [ 7 12 28]
  [ 7 12 28]]

 [[31 17 21]
  [30 17 21]
  [28 18 21]
  ...
  [ 7  7 24]
  [ 8  8 25]
  [ 9  9 26]]

 [[30 16 20]
  [30 17 21]
  [28 18 21]
  ...
  [ 6  4 23]
  [ 7  5 24]
  [ 8  6 25]]]
[[[34 81 73]
  [37 81 74]
  [42 80 74]
  ...
  [15 10 15]
  [17 10 17]
  [17  9 16]]

 [[43 87 80]
  [44 86 79]
  [45 82 76]
  ...
  [12  8 14]
  [15  8 16]
  [15  7 16]]

 [[42 83 76]
  [44 82 76]
  [44 78 74]
  ...
  [10  7 16]
  [13  7 18]
  [14  7 18]]

 ...

 [[15 21 14]
  [16 20 14]
  [17 20 15]
  ...
  [20 11 24]
  [21 11 24]
  [22 12 25]]

 [[20 24 19]
  [21 25 20]
  [21 24 19]
  ...
  [18  9 22]
  [18  8 21]
  [19  9 21]]

 [[23 27 22]
  [25 28 23]
  [25 27 22]
  .

[[[72 72 72]
  [72 73 74]
  [68 72 74]
  ...
  [15  5 24]
  [18  7 26]
  [19  7 25]]

 [[71 72 73]
  [68 70 71]
  [63 67 71]
  ...
  [14  4 23]
  [17  6 25]
  [17  5 24]]

 [[66 68 71]
  [62 65 69]
  [57 62 67]
  ...
  [14  5 23]
  [18  7 26]
  [19  7 26]]

 ...

 [[33 16 26]
  [32 14 24]
  [31 13 23]
  ...
  [10 16 22]
  [11 18 21]
  [11 18 20]]

 [[28 15 24]
  [27 14 23]
  [28 13 23]
  ...
  [11 16 20]
  [11 17 19]
  [11 17 19]]

 [[25 14 24]
  [26 14 24]
  [26 14 24]
  ...
  [13 18 20]
  [14 19 21]
  [14 19 20]]]
[[[63 80 76]
  [66 81 76]
  [67 79 74]
  ...
  [ 2  6 14]
  [ 1 12 14]
  [ 1 15 14]]

 [[60 77 73]
  [63 78 74]
  [64 75 70]
  ...
  [ 1  5 13]
  [ 0  9 13]
  [ 0 11 12]]

 [[61 77 74]
  [65 79 75]
  [62 72 69]
  ...
  [ 1  5 13]
  [ 0  8 14]
  [ 0 11 16]]

 ...

 [[22 16 18]
  [22 16 18]
  [22 16 18]
  ...
  [14 13 18]
  [16 15 18]
  [15 14 17]]

 [[28 17 22]
  [26 17 21]
  [26 17 21]
  ...
  [17 14 23]
  [19 15 23]
  [19 15 23]]

 [[31 19 25]
  [29 18 24]
  [28 17 23]
  .

In [1]:
pip install virtualenv # to be done in anaconda cmd

Note: you may need to restart the kernel to use updated packages.


The filename, directory name, or volume label syntax is incorrect.


In [2]:
pip install flask # to be done in anaconda cmd

Note: you may need to restart the kernel to use updated packages.


The filename, directory name, or volume label syntax is incorrect.
